baseURL: 'https://clubalgoritmiaus.es'
title: Club de Algoritmia de la Universidad de Sevilla
DefaultContentLanguage: es
disableLanguages: []
defaultContentLanguageInSubdir: false
languages:
  es:
    languageName: Espa√±ol
    weight: 1
  en:
    languageName: English
    weight: 2
    
# defaultContentLanguageInSubdir: false
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: true
pagination:
  pagerSize: 9
darkmode_js:
  - assets/js/darkmode.js
enableInlineShortcodes: true

params:
  title_short: CAUS
  author: Club Algoritmia de la Universidad de Sevilla
  authorimage: ../assets/images/global/author-CAUS.webp  # caus-web/assets/images/global/author-CAUS.webp
  heropic: /images/pages/logo_CAUS.png
  og_image: /images/logo-CAUS.png # caus-web/static/images/logo-CAUS.png
  disable_theme_toggle: false
  disable_stay_uptodate: false

  p1:
    image: "images/pages/complicaus-v.webp" 
  p2:
    image: "images/pages/roco.jpg"
  p3:
    links:
        - url: "/community-partners"
    logos:
      - identifier: a
        image: "images/global/Logo_ND.png" 
        alt: "a"
      - identifier: b
        image: "images/global/logo-ETSII-Color.png"
        alt: "b"
      # - identifier: c
      #   image: "images/global/Logo_ND.png" 
      #   alt: "c"
      # - identifier: d
      #   image: "images/global/logo-ETSII-Color.png"
        # alt: "d"

  social_media:
    github:
      enabled: true
      url: 'https://github.com/algoritmiaUS'
    linkedin:
      enabled: true
      url: 'https://linkedin.com/company/club-de-algoritmia-universidad-de-sevilla'
    whatsapp:
      enabled: true
      url: 'https://chat.whatsapp.com/DFm3DnLHbGn4vWimWN1Wmc'
    instagram:
      enabled: true
      url: 'https://instagram.com/clubalgoritmiaus'
    twitter:
      enabled: true
      url: 'https://x.com/algoritmiaus'
    youtube:
      enabled: true
      url: 'https://www.youtube.com/@ClubAlgoritmiaUS'
    

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer:
        apostrophe: '&rsquo;'
        disable: false
        ellipsis: '&hellip;'
        emDash: '&mdash;'
        enDash: '&ndash;'
        leftAngleQuote: '&laquo;'
        leftDoubleQuote: '&ldquo;'
        leftSingleQuote: '&lsquo;'
        rightAngleQuote: '&raquo;'
        rightDoubleQuote: '&rdquo;'
        rightSingleQuote: '&rsquo;'
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

# markup:
#   goldmark:
#     renderer:
#       unsafe: true

taxonomies:
  category: Categories
  tag: Tags

privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: false
    useSessionStorage: false
  instagram:
    disable: false
    simple: false
  twitter:
    disable: false
    enableDNT: false
    simple: false
  vimeo:
    disable: false
    enableDNT: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true

module:
  hugoVersion:
    extended: true
    min: "0.104.0"
